In [1]:
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from warnings import filterwarnings
filterwarnings('ignore')

## Reading Dataset

In [2]:
df = pd.read_csv('IOT_Assignment_2_data_regression_sensor_range.csv')
df.columns = ['Humidity', 'Temperature', 'Waterflow']
df.head()

Humidity  Temperature  Waterflow
0  25.045045    76.856857  67.432607
1   8.880881    31.771772   0.000000
2  24.956957    75.735736  66.105904
3  40.328328    88.308308   0.000000
4  38.742743    57.157157   0.000000

In [3]:
df.describe()

Humidity  Temperature   Waterflow
count  200.000000   200.000000  200.000000
mean    31.137437    59.747347   25.496364
std     12.386344    23.112767   34.953661
min      8.132132    20.000000    0.000000
25%     21.015015    40.860861    0.000000
50%     30.616617    58.638639    0.000000
75%     41.528529    78.998999   61.884829
max     51.867868   100.000000  100.000000

## Perform Min Max Scaling on Features

In [4]:
X = df[['Humidity','Temperature']]
scaler = MinMaxScaler()
X = scaler.fit_transform(X)
y = df.Waterflow

## Splitting Dataset into training and testing

In [5]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

##  Implementing MLP Regressor and Finding the accuracy

In [6]:
from sklearn.metrics import mean_squared_error
# The value of random_state=56 have been achieved after running a loop ranging from 0 to 100
model = MLPRegressor(activation='relu', hidden_layer_sizes=(16,8),random_state = 56, max_iter=8000).fit(x_train, y_train)
y_pred = model.predict(x_test)
rms = mean_squared_error(y_test, y_pred, squared=False)
print("r2_score: ", (r2_score(y_pred, y_test)), ",accuracy",model.score(x_test, y_test), ",rmse:",rms)

r2_score:  0.8355453119132263 ,accuracy 0.8607942724220553 ,rmse: 12.777447968938661


## Testing on some sample values

In [7]:
model.predict(x_test[2].reshape(1,2))

array([75.41138601])

In [8]:
model.predict(x_test[4].reshape(1,2))

array([77.16078806])

## Weights of the model

In [9]:
model.coefs_

[array([[ 2.95845826e+000,  2.62680294e-151,  1.68454723e+000,
         -3.71697493e-001, -4.13991150e+000,  8.53281870e-001,
          4.39498957e-133,  2.49949929e+000,  2.05022038e+000,
          4.44919735e-165, -1.02592115e+000, -8.84529456e-106,
          1.16865229e+000, -2.48378582e+000, -1.12685780e+000,
         -1.52749588e+000],
        [ 3.70581235e+000,  1.07164200e-136,  1.48084828e-001,
          3.99229036e-001,  1.44800993e+000,  2.14375537e+000,
         -4.57236513e-098, -5.34739780e-001,  4.56226909e-001,
          5.09892594e-175,  5.62606743e-001,  1.16763444e-137,
          2.49084092e+000,  2.61039197e+000,  5.92053689e-001,
          2.11379273e+000]]),
 array([[-5.41265446e-001,  3.40952564e+000, -4.34539424e+000,
          4.05294487e+000,  4.58219508e+000,  3.54417762e+000,
         -4.15116210e+000, -5.49907549e+000],
        [ 5.66518419e-124, -1.25183800e-103, -5.31111317e-179,
          2.19274267e-107,  2.09822413e-143,  6.62536393e-154,
         -8.30

## Bias of the model

In [10]:
model.intercepts_

[array([-4.76382938, -0.17346785,  1.28525358, -0.38122354,  1.01136797,
        -0.61966671, -0.41820093,  0.47967465,  0.26725188, -0.39660994,
         0.70402991, -0.38643418, -0.56158533, -0.42316934,  0.78626603,
        -0.46513269]),
 array([ 1.2152304 ,  0.13011387,  1.04728916,  0.49993377,  0.12602774,
         0.10195648,  2.20141629, -0.41615318]),
 array([0.28850515])]